version: 2
jobs:
  dependencies:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Node dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  lint:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Lint
          command: yarn lint

  flow:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Flow
          command: yarn flow

  unit:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Unit tests
          command: yarn test:unit

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Dependencies
          command: cd example && npm install
      - run:
          name: Git config
          command: |
            git config user.email "contact@vincent-catillon.fr"
            git config user.name "Vincent Catillon"
      - run:
          name: Deploy
          command: cd example && npm run deploy
      - add_ssh_keys:
          fingerprints:
            - "d2:d6:b7:cd:fa:2e:78:03:f4:2f:06:9a:3f:a4:c0:45"

workflows:
  version: 2
  tests:
    jobs:
      - dependencies
      - lint:
         requires:
           - dependencies
      - flow:
         requires:
           - dependencies
      - unit:
         requires:
           - dependencies
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
