version: 2
jobs:
  dependencies:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Node dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  lint:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Lint
          command: yarn lint

  flow:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Flow
          command: yarn flow

  unit:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Unit tests
          command: yarn test:unit

workflows:
  version: 2
  tests:
    jobs:
      - dependencies
      - lint:
         requires:
           - dependencies
      - flow:
         requires:
           - dependencies
      - unit:
         requires:
           - dependencies
